  - type: rpm-ostree
    repos:
      # Hyprland
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      # Hyprland
      - hyprland
      - xdg-desktop-portal-hyprland
      - xorg-x11-server-Xwayland

      # shell
      - aylurs-gtk-shell